version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: course
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
